Add local Artifactory setup
jfrog/jfrog-testing-infra pull request #5
Opened 2022-01-11 13:46 UTC by RobiNino

2022-01-12 16:25 UTC, yahavi requested changes
Big like @RobiNino!

* Please add a description in the README file.
* Optional feature request after the merge, if you want to harden the security 💪🏼 - Do all of this in a new random user with a random password. Switch back to the original user after everything is done.

2022-01-12 16:25 UTC, yahavi commented on main.go
> +		e := os.Setenv(licenseEnv, "")
```suggestion
		e := os.Unsetenv(licenseEnv)
```

2022-01-12 16:25 UTC, yahavi commented on main.go
> +			log.Println("error when unsetting env: " + e.Error())
e may be nil.
I'm not sure what you're trying to do here.

2022-01-12 16:25 UTC, yahavi commented on main.go
> +	cmd.Stdout = os.Stderr
Isn't it the default?

2022-01-12 16:25 UTC, yahavi commented on main.go
> +func renameArtifactoryDir(jfrogHome string) error {
Please add documentation about this function, since it is not clear enough

2022-01-13 09:54 UTC, RobiNino commented on main.go
> +	cmd.Stdout = os.Stderr
No:
```
	// If either is nil, Run connects the corresponding file descriptor
	// to the null device (os.DevNull).

2022-01-13 10:21 UTC, RobiNino commented on main.go
> +			log.Println("error when unsetting env: " + e.Error())
Wanted to log the error if both e and err are not nil. Added a nil check.

2022-01-16 07:30 UTC, eyalbe4 requested changes
* I think it'll be better if the gradle and the go code will be located in separate directories under the root fo the project. This way, you'll have the go.mod and go.sum on the root of a sub project, and the same goes for the build.gradle and settins.gradle.
* The README of the project should be up to date with the new content of this project.

2022-01-16 08:43 UTC, eyalbe4 requested changes

2022-01-16 12:03 UTC, RobiNino commented
Done, you are welcome to review again @eyalbe4 , @yahavi .
I named the subdirectory `local-rt-setup` so we can install it using `go install`. `go install` names the binary by the last directory name (doesn't support providing a different name). Calling the directory `go` would cause confusion with the actual `go` binary.

2022-01-16 14:05 UTC, yahavi approved these changes
LGTM

2022-01-17 09:25 UTC, merged